# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlog',
            name='TEventID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
