DROP TABLE IF EXISTS `hremp_rec`;

CREATE TABLE hremp_rec (
    home_tpos_no integer,
    id integer DEFAULT 0 NOT NULL,
    ss_first varchar(32) NOT NULL,
    ss_middle varchar(32) NOT NULL,
    ss_last varchar(50) NOT NULL,
    ss_suffix varchar(10) NOT NULL,
    vac char(1),
    term char(1),
    negotiate char(1),
    tenure char(1),
    tenure_date date,
    stat char(1),
    pseudo_serial integer,
    dir_dep char(1),
    ofc_for_ck varchar(4),
    self_emp char(1),
    minister char(1),
    pension char(1),
    union_ind char(1),
    union_class varchar(4),
    union_code varchar(4),
    tiaa_no varchar(12),
    sty_code char(1),
    legal_rep char(1),
    empl942 char(1),
    cl varchar(4),
    pt char(1),
    tmp char(1),
    dist char(1),
    cntrct_sal decimal(16,2),
    mos_paid integer,
    is_tenure_track char(1),
    is_tenured char(1),
    primocc varchar(2),
    tsoc2010 varchar(7),
    is_soft_money char(1),
    eeoc_sort char(1),
    is_reg char(1),
    hrretgrp varchar(8),
    contrib_max_amt decimal(16,2) DEFAULT 0.00,
    tsocmaj varchar(2),
    socdtl varchar(4),
    ipeds_rptg_stat varchar(4),
    ipeds_instrn_stat varchar(10),
    ipeds_acad_rank varchar(8),
    ipeds_is_medical char(1) DEFAULT 'N',
    ipeds_grad_assist char(1) DEFAULT 'N',
    ipeds_mos_wrkd varchar(2) DEFAULT '12',
    ipeds_new_hire_date date
);
CREATE INDEX hremp_key1 ON hremp_rec (id,home_tpos_no);
CREATE UNIQUE INDEX hremp_prim ON hremp_rec (id);