INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('ATDR', 'Athletic Director', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('CHAP', 'Chapel', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('CONF', 'Conference', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('DOS', 'Dean of Students', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('DOSC', 'Dean of Seibert Chapel', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('EDUC', 'Education Division', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('EMER', 'Emeritus', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('FIAR', 'Fine Arts Division', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('HUMN', 'Humanities Division', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('IDST', 'Interdisciplinary Study', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('NATS', 'Natural Science Division', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('PRES', 'President', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('PROV', 'Provost', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('SOCS', 'Social Science Division', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('VPAB', 'VP Admin & Business', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('VPAD', 'VP Adult Education', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('VPCO', 'VP College Relations', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('VPEN', 'VP Enrollment', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('VPLI', 'VP Library', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('VEND', 'Carthage Vendor', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('PRDV', 'Professional Develop', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('PEND', 'Pending', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('STUD', 'Student Worker', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('VPAR', 'Sen VP Academic Resource', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('VPCR', 'VP Church Relations', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('501', 'Business Office', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('VPIA', 'Sen VP Inst Advancement', '2012-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('303', 'LIS', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('203', 'Chapel Office', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('205', 'Athletics', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('207', 'Admissions Office', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('208', 'Financial Aid Officd', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('301', 'Provost Office', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('302', 'Registrars Office', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('314', 'Heritage', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('352', 'Career Center', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('354', 'Advising Office', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('356', 'Writing Center', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('390', 'Humanities', '2010-09-01', '2018-03-15');
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('391', 'Social Science', '2010-09-01', '2018-03-15');
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('392', 'Natural & Social Sci Div', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('393', 'Professional Studies Div', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('394', 'Arts & Humanities Div', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('401', 'Dean of Students', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('402', 'Residential Assistance', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('406', 'Communications Office', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('505', 'Mailroom', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('602', 'Sodexo', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('605', 'Conferences', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('610', 'TARC', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('405', 'Instit Advancement', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('601', 'Bookstore', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('202', 'Presidents Office', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('304', 'Adult Education', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('319', 'Pep Band', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('349', 'Classics', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('404', 'Health Counseling Center', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('511', 'Security', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('516', 'Environmental Services', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('604', 'TWC', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('752', 'Community Service', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('857', 'Current', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('858', 'Student Government', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('859', 'Driftwood', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('860', 'CAB', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('862', 'Centrigue', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('351', 'Graduate Office', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('320', 'Biology Dept', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('395', 'Student Fellowships', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('512', 'Maintenance', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('BUSA', 'Business Administration', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('215', 'Domin Soccer Camp', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('412', 'Church Relations', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('358', 'Tutoring', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('359', 'SI', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('NURS', 'Nursing Division', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('305', 'Media', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('308', 'Infrastructure', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('SDSC', 'Student Success', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('200', 'Strategic Initiatives', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('322', 'WSGC', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('411', 'Celebrations', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('PRFS', 'Professional Studies', '2015-07-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('NSSS', 'Nat and Soc Science', '2015-07-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('ARHU', 'Arts and Humanities', '2015-07-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('PRST', 'Professional Studies', '2015-07-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('ACPR', 'All College Programs', '2015-07-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('201', 'Board of Trustees', '2015-07-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('316', 'Grants', '2015-07-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('410', 'Sports Info', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('311', 'Continuing Studies', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('327', 'Music Department', '2010-09-01', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('517', 'Shuttle Driver', '2016-09-04', null);
INSERT INTO hrdiv_table(hrdiv, descr, beg_date, end_date) VALUES ('333', 'Modern Language', '2017-01-01', null);
