INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('BIO', 'NATS', 'Biology Department', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('BSOF', 'VPAB', 'Business Office', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('ATH', 'ATDR', 'Athletic Department', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('PRES', 'ATDR', 'Officer of the College', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('PRES', 'CHAP', 'Officer of the College', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('DOS', 'DOS', 'Dean of Students Office', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('PRES', 'DOS', 'Officer of the College', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('PRES', 'EMER', 'Emeritus Status', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('REGI', 'EMER', 'Emeritus Status', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('DEVE', 'EMER', 'Emeritus Status', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('LIS', 'EMER', 'Emeritus Status', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('PRES', 'PRES', 'President''s Office', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('CARE', 'PROV', 'Career Services', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('PROV', 'PROV', 'Provost''s Office', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('NATS', 'PROV', 'Natural Science Division', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('PRES', 'PROV', 'Officer of the College', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('CONF', 'VPAB', 'Conference Department', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('BOOK', 'VPAB', 'Bookstore', '2010-09-01', '2010-09-01');
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('MAIN', 'VPAB', 'Maintenance Department', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('PRES', 'VPAB', 'Officer of the College', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('ADUL', 'VPAD', 'Continuing Studies', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('PRES', 'VPAD', 'Officer of the College', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('DEVE', 'VPCO', 'College Relations Office', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('PRES', 'VPCO', 'Officer of the College', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('ADVS', 'VPEN', 'Advising Office', '2010-09-01', '2010-09-01');
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('REGI', 'VPEN', 'Registrar''s Office', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('FINA', 'VPEN', 'Financial Aid Office', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('ADMS', 'VPEN', 'Admissions Office', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('PRES', 'VPEN', 'Officer of the College', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('LIS', 'VPLI', 'Library Info Services', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('PRES', 'VPLI', 'Officer of the College', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('GM', 'PRES', 'Gospel Messengers', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('PEP', 'PRES', 'Pep Band', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('BIO', 'PROV', 'Biology Department', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('BUS', 'PROV', 'Business Admin Depart', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('CHM', 'PROV', 'Chemistry Department', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('CLS', 'PROV', 'Classics Department', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('CDM', 'PROV', 'Comm Digital Media Dept', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('CSC', 'PROV', 'Computer Science Dept', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('ART', 'PROV', 'Art Department', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('FIAR', 'PROV', 'Fine Arts Division', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('ECN', 'PROV', 'Economics Department', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('EDU', 'PROV', 'Education Department', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('EDUC', 'PROV', 'Education Division', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('ENG', 'PROV', 'English Department', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('EXS', 'PROV', 'EXSS Department', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('GEO', 'PROV', 'Geography and Earth Sci', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('HIS', 'PROV', 'History Department', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('HUMN', 'PROV', 'Humanities Division', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('IDST', 'PROV', 'Interdisciplinary Study', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('MTH', 'PROV', 'Math Department', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('MLA', 'PROV', 'Mod Language Department', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('MUS', 'PROV', 'Music Department', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('PHL', 'PROV', 'Philosophy Department', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('PHY', 'PROV', 'Physics/Astronomy Dept', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('POL', 'PROV', 'Political Science Dept', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('PYC', 'PROV', 'Psychological Science', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('REL', 'PROV', 'Religion Department', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('SOCS', 'SOCS', 'Social Science Division', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('SOCS', 'PROV', 'Social Science Division', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('SWK', 'PROV', 'Social Work Department', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('SOC', 'PROV', 'Sociology Department', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('THR', 'PROV', 'Theatre Department', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('_CRJ', 'PROV', 'Criminal Justice Program', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('_DIS', 'PROV', 'Discovery Program', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('_GBL', 'PROV', 'Global Heritage Program', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('_GFW', 'PROV', 'Great Ideas Program', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('_IPE', 'PROV', 'Intern''l Political Econ', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('_NEU', 'PROV', 'Neuroscience Program', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('_SSC', 'PROV', 'Social Science Program', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('EDU', 'EDUC', 'Education Department', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('EXS', 'EDUC', 'Exercise & Sport Science', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('BUS', 'EMER', 'Emeritus Status', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('ART', 'EMER', 'Emeritus Status', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('BIO', 'EMER', 'Emeritus Status', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('CHM', 'EMER', 'Emeritus Status', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('_CRJ', 'EMER', 'Emeritus Status', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('ECN', 'EMER', 'Emeritus Status', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('EDU', 'EMER', 'Emeritus Status', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('ENG', 'EMER', 'Emeritus Status', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('EXS', 'EMER', 'Emeritus Status', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('MLA', 'EMER', 'Emeritus Status', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('HIS', 'EMER', 'Emeritus Status', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('MTH', 'EMER', 'Emeritus Status', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('MUS', 'EMER', 'Emeritus Status', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('PHL', 'EMER', 'Emeritus Status', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('PHY', 'EMER', 'Emeritus Status', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('POL', 'EMER', 'Emeritus Status', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('REL', 'EMER', 'Emeritus Status', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('_SSC', 'EMER', 'Emeritus Status', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('SOC', 'EMER', 'Emeritus Status', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('ART', 'FIAR', 'Art Department', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('CDM', 'FIAR', 'Comm Digital Media Dept', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('MUS', 'FIAR', 'Music Department', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('THR', 'FIAR', 'Theatre Department', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('CLS', 'HUMN', 'Classics Department', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('ENG', 'HUMN', 'English Department', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('HIS', 'HUMN', 'History Department', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('MLA', 'HUMN', 'Mod Language Department', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('PHL', 'HUMN', 'Philosophy Department', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('REL', 'HUMN', 'Religion Department', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('_GOV', 'HUMN', 'Government Department', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('_GFW', 'IDST', 'Great Ideas Program', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('CHM', 'NATS', 'Chemistry Department', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('CSC', 'NATS', 'Computer Science Dept', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('GEO', 'NATS', 'Geography and Earth Sci', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('MTH', 'NATS', 'Math Department', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('_NEU', 'NATS', 'Neuroscience Program', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('PHY', 'NATS', 'Physics/Astronomy Dept', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('BUS', 'SOCS', 'Business Admin Depart', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('ECN', 'SOCS', 'Economics Department', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('POL', 'SOCS', 'Political Science Dept', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('PYC', 'SOCS', 'Psychological Science', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('SWK', 'SOCS', 'Social Work Department', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('SOC', 'SOCS', 'Sociology Department', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('_CRJ', 'SOCS', 'Criminal Justice Program', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('_ATH', 'EDUC', 'Athletic Training Progrm', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('_PEH', 'EDUC', 'PE/Health Program', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('_GBL', 'IDST', 'Global Heritage Program', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('_WHE', 'IDST', 'Western Heritage Program', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('PARA', 'VPAD', 'Paralegal Program', '2010-09-01', '2010-09-02');
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('CHAP', 'CHAP', 'Chapel Office', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('EVS', 'VPAB', 'Environmental Services', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('SECU', 'VEND', 'Security', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('FOOD', 'VEND', 'Sodexo', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('MSW', 'VEND', 'Loyola MSW', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('BOOK', 'VEND', 'Barnes & Noble Bookstore', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('ADVS', 'DOS', 'Advising Office', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('CHWK', 'PRDV', 'Chiwaukee', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('ENRC', 'PRDV', 'Enrichment', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('KUSD', 'PRDV', 'Kenosha Unified', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('PARA', 'PRDV', 'Paralegal Program', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('_GNR', 'IDST', 'General', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('PEND', 'PEND', 'Pending Employee', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('ACT', 'PRDV', 'ACT Program', '1900-01-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('STUD', 'STUD', 'Student Worker', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('REGI', 'VPAR', 'Registrar''s Office', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('PRES', 'VPAR', 'Officer of the College', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('DEVE', 'VPAR', 'College Relations Office', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('PRES', 'VPCR', 'Officer of the College', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('WRC', 'PROV', 'Writing Center', '1900-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('MAIL', 'VPLI', 'Mailroom', '1900-01-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('ADAS', 'PROV', 'Faculty Admin Asst', '1900-01-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('_ENT', 'NATS', 'Entrepreneurship', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('_ASN', 'PROV', 'Asian Studies Program', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('_HON', 'PROV', 'Honors Program', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('_WHE', 'PROV', 'Western Heritage Program', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('_WMG', 'PROV', 'Women & Gender Studies', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('_ENV', 'PROV', 'Environmental Science', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('_ESN', 'PROV', 'Science Works Program', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('CSC', 'EMER', 'Emeritus Status', '1900-01-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('PROV', 'EMER', 'Emeritus Status', '1900-01-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('MBA', 'VEND', 'Loyola Executive MBA', '2010-09-01', '2012-08-31');
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('KUSD', 'VEND', 'KUSD Instructors', '1900-01-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('HCC', 'DOS', 'Health & Counseling Cntr', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('_SSC', 'SOCS', 'Social Science Program', '1900-01-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('ATH', 'VEND', 'Athletic Department', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('_WMG', 'IDST', 'Women & Gender Studies', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('_ASN', 'IDST', 'Asian Studies Program', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('055', '501', 'Business Office Wrkstdy', '1900-01-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('IA', 'VPIA', 'Institutional Advancemnt', '2012-09-17', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('IA', 'EMER', 'Emeritus Status', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('COMM', 'VPIA', 'Communications Office', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('_ESN', 'NATS', 'Entrepreneurial Studies', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('EDUC', 'VEND', 'Education Department', '1900-01-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('050', '501', 'Business Office CE', '1900-01-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('GRNT', 'PROV', 'Grants & Sponsored Prog', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('FIAR', 'VEND', 'Fine Arts Division', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('_ENV', 'NATS', 'Environmental Science', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('050', '303', 'LIS CE', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('050', '203', 'Chapel CE', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('050', '205', 'Athletics CE', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('050', '207', 'Admissions Office CE', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('050', '208', 'Financial Aid Office CE', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('050', '301', 'Provost Office CE', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('302', '302', 'Registrar Office CE', '2010-09-01', '2010-09-01');
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('050', '314', 'Heritage CE', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('050', '352', 'Career Center CE', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('050', '354', 'Advising Office CE', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('050', '356', 'Writing Center CE', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('050', '302', 'Registrar Office CE', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('050', '390', 'Humanities CE', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('050', '391', 'Social Science CE', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('050', '392', 'Natural Science CE', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('050', '393', 'Education CE', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('050', '394', 'Fine Arts CE', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('050', '401', 'Dean of Students CE', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('002', '402', 'Residential Assistant CE', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('050', '405', 'Instit Advancement CE', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('050', '406', 'Communications Office CE', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('050', '505', 'Mailroom CE', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('050', '602', 'Sodexo CE', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('050', '605', 'Conferences CE', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('050', '610', 'TARC CE', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('050', '601', 'Bookstore CE', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('050', '202', 'Presidents Office CE', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('055', '202', 'Presidents Office FWS', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('055', '203', 'Chapel FWS', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('055', '205', 'Athletics FWS', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('055', '207', 'Admissions Office FWS', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('055', '208', 'Financial Aid Office FWS', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('055', '301', 'Provost Office FWS', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('055', '302', 'Registrars Office FWS', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('055', '303', 'LIS FWS', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('050', '304', 'Adult Education CE', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('055', '314', 'Heritage FWS', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('050', '319', 'Pep Band CE', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('055', '319', 'Pep Band FWS', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('055', '304', 'Adult Education FWS', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('050', '349', 'Classics CE', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('055', '349', 'Classics FWS', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('055', '352', 'Career Center FWS', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('055', '354', 'Advising Office FWS', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('055', '356', 'Writing Center FWS', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('055', '390', 'Humanities FWS', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('055', '391', 'Social Science FWS', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('055', '392', 'Natural Science FWS', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('055', '393', 'Education FWS', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('055', '394', 'Fine Arts FWS', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('055', '401', 'Dean of Students FWS', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('050', '404', 'HCC CE', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('055', '404', 'HCC FWS', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('055', '405', 'Instit Advancement FWS', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('055', '406', 'Communications Off FWS', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('055', '505', 'Mailroom FWS', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('050', '511', 'Security CE', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('055', '511', 'Security FWS', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('050', '516', 'EVS CE', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('055', '516', 'EVS FWS', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('055', '601', 'Bookstore FWS', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('055', '602', 'Sodexo FWS', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('050', '604', 'TWC CE', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('055', '604', 'TWC FWS', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('055', '605', 'Conferences FWS', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('055', '610', 'TARC FWS', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('050', '752', 'Community Service CE', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('055', '752', 'Community Service FWS', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('050', '857', 'Current CE', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('050', '858', 'Student Government CE', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('050', '859', 'Driftwood CE', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('050', '860', 'CAB CE', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('050', '862', 'Centrigue CE', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('055', '857', 'Current FWS', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('055', '858', 'Student Government FWS', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('055', '859', 'Driftwood FWS', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('055', '860', 'CAB FWS', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('055', '862', 'Centrigue FWS', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('055', '402', 'RA FWS', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('107', '205', 'Sports Info', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('050', '351', 'Graduate Office CE', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('932', '352', 'Internship', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('280', '320', 'EREN Grant', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('050', '395', 'Student Fellowships CE', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('055', '395', 'Student Fellowships FWS', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('050', '512', 'Maintenance CE', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('055', '512', 'Maintenance FWS', null, null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('MLA', 'PRES', 'China Internship', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('360', '205', 'Swim Lessons', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('FAC', 'BUSA', 'Finance and Accounting', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('MMK', 'BUSA', 'Management and Marketing', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('050', '215', 'Domin Soccer Camp', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('050', '412', 'Church Relations CE', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('055', '412', 'Church Relations FWS', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('050', '358', 'Tutoring CE', '2013-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('055', '358', 'Tutoring FWS', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('050', '359', 'SI CE', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('055', '359', 'SI FWS', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('MMK', 'PROV', 'Management and Marketing', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('FAC', 'PROV', 'Finance and Accounting', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('NUR', 'NURS', 'Nursing Department', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('WSGC', 'PROV', 'Wisconsin Space Grant', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('050', '305', 'Media CE', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('055', '305', 'Media FWS', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('050', '308', 'Infrastructure CE', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('055', '308', 'Infrastructure FWS', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('725', '406', 'Tarble Arena', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('786', '202', 'Church Relations', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('SDSC', 'SDSC', 'Student Success Office', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('SSC', 'SOCS', 'Social Science Program', '2010-09-01', '2010-09-01');
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('TSI', 'PROV', 'Tutoring and SI', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('055', '200', 'Strategic Initiatives FW', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('050', '200', 'Strategic Initiatives CE', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('CDM', 'EMER', 'Emeritus Status', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('050', '322', 'WSGC CE', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('055', '322', 'WSGC FWS', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('610', '411', 'Celebrations CE', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('FAC', 'PRFS', 'Accounting and Finance', '2015-07-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('FAC', 'PRST', 'Finance and Accounting', '2015-07-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('EDU', 'PRST', 'Education Department', '2015-07-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('EXS', 'PRST', 'Exercise & Sport Science', '2015-07-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('MMK', 'PRST', 'Management and Marketing', '2015-07-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('NUR', 'PRST', 'Nursing Department', '2015-07-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('SWK', 'PRST', 'Social Work Department', '2015-07-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('ATH', 'PRST', 'Athletic Training', '2015-07-01', '2015-07-01');
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('_ATH', 'PRST', 'Athletic Training', '2015-07-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('_ESN', 'PRST', 'Entrepreneurial Studies', '2015-07-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('_PEH', 'PRST', 'PE/Health Program', '2015-07-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('SWK', 'EMER', 'Emeritus Status', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('CHM', 'NSSS', 'Chemistry Department', '2015-07-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('PYC', 'NSSS', 'Psychological Science', '2015-07-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('CDM', 'ARHU', 'Comm Digital Media Dept', '2015-07-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('_NEU', 'NSSS', 'Neuroscience Program', '2015-07-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('BIO', 'NSSS', 'Biology Department', '2015-07-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('CSC', 'NSSS', 'Computer Science Dept', '2015-07-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('MUS', 'ARHU', 'Music Department', '2015-07-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('THR', 'ARHU', 'Theatre Department', '2015-07-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('REL', 'ARHU', 'Religion Department', '2015-07-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('_WHE', 'ACPR', 'Western Heritage Program', '2015-07-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('MLA', 'ARHU', 'Mod Language Department', '2015-07-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('ECON', 'NSSS', 'Economics', '2015-07-01', '2015-07-01');
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('ART', 'ARHU', 'Art Department', '2015-07-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('CLS', 'ARHU', 'Classics Department', '2015-07-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('ENG', 'ARHU', 'English Department', '2015-07-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('HIS', 'ARHU', 'History Department', '2015-07-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('ARHU', 'PROV', 'Arts/Humanities Div', '2015-07-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('PRST', 'PROV', 'Professional Studies Div', '2015-07-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('NSSS', 'PROV', 'Natural/Social Science', '2015-07-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('PHL', 'ARHU', 'Philosophy Department', '2015-07-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('_ASN', 'ARHU', 'Asian Studies Program', '2015-07-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('_GFW', 'ARHU', 'Great Ideas Program', '2015-07-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('_WMG', 'ARHU', 'Women & Gender Studies', '2015-07-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('ECN', 'NSSS', 'Economics Department', '2015-07-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('GEO', 'NSSS', 'Geography and Earth Sci', '2015-07-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('MTH', 'NSSS', 'Math Department', '2015-07-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('PHY', 'NSSS', 'Physics/Astronomy Dept', '2015-07-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('POL', 'NSSS', 'Political Science Dept', '2015-07-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('PYC', 'EMER', 'Emeritus Status', '2015-07-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('SOC', 'NSSS', 'Sociology Department', '2015-07-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('_SSC', 'NSSS', 'Social Science Program', '2015-07-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('_CRJ', 'NSSS', 'Criminal Justice Program', '2015-07-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('_ENV', 'NSSS', 'Environmental Science', '2015-07-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('_GBL', 'ACPR', 'Global Heritage Program', '2015-07-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('_HON', 'ACPR', 'Honors Program', '2015-07-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('_IPE', 'NSSS', 'Intern''l Political Econ', '2015-07-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('ACPR', 'PROV', 'All College Programs', '2015-07-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('050', '201', 'Board of Trustees CE', '2015-07-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('055', '201', 'Board of Trustees FWS', '2015-07-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('050', '316', 'Grants CE', '2015-07-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('055', '316', 'Grants FWS', '2015-07-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('_NAT', 'NSSS', 'Natural Science Program', '2015-07-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('_MTR', 'ACPR', 'Mock Trial', '2015-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('050', '410', 'Sports Info CE', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('055', '410', 'Sports Info FWS', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('_GNR', 'ACPR', 'General', '2015-07-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('050', '311', 'Continuing Studies CE', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('055', '311', 'Continuing Studies FWS', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('123', '352', 'Great Lakes Internship', '2015-07-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('_SSC', 'PRST', 'Social Science Program', '2016-07-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('470', '327', 'Community Piano Program', '2010-09-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('050', '517', 'Shuttle Driver CE', '2016-09-04', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('014', '333', 'TLE Adjunct', '2017-01-01', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('055', '517', 'Shuttle Driver FWS', '2017-09-22', null);
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('059', '205', 'Athletics GRD', '2017-10-13', '2017-10-14');
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('361', '205', 'Swim Lessons GRD', '2017-10-13', '2017-10-14');
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('059', '314', 'All College Prog GRD', '2017-10-13', '2017-10-14');
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('059', '393', 'Education GRD', '2017-10-13', '2017-10-14');
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('059', '610', 'TARC GRD', '2017-10-13', '2017-10-14');
INSERT INTO hrdept_table(hrdept, hrdiv, descr, beg_date, end_date) VALUES ('059', '358', 'Tutoring GRD', '2017-10-13', '2017-10-14');
