INSERT INTO hrstat_table(hrstat, txt, active_date, inactive_date) VALUES ('FT', 'FT Faculty', null, null);
INSERT INTO hrstat_table(hrstat, txt, active_date, inactive_date) VALUES ('PT', 'Part-time Fac Day', null, null);
INSERT INTO hrstat_table(hrstat, txt, active_date, inactive_date) VALUES ('LV', 'On Leave', null, '2016-07-01');
INSERT INTO hrstat_table(hrstat, txt, active_date, inactive_date) VALUES ('DA', 'Disability Leave', null, '2016-07-01');
INSERT INTO hrstat_table(hrstat, txt, active_date, inactive_date) VALUES ('SA', 'Sabbatical', null, '2016-07-01');
INSERT INTO hrstat_table(hrstat, txt, active_date, inactive_date) VALUES ('REG', 'Regular Employee', null, '2016-07-01');
INSERT INTO hrstat_table(hrstat, txt, active_date, inactive_date) VALUES ('STU', 'Student Work Study', null, null);
INSERT INTO hrstat_table(hrstat, txt, active_date, inactive_date) VALUES ('AD', 'Administration', null, null);
INSERT INTO hrstat_table(hrstat, txt, active_date, inactive_date) VALUES ('HR', 'Hourly Employee', null, null);
INSERT INTO hrstat_table(hrstat, txt, active_date, inactive_date) VALUES ('HRPT', 'Part-time Hourly', null, null);
INSERT INTO hrstat_table(hrstat, txt, active_date, inactive_date) VALUES ('PATH', 'Part-time Athletics', null, null);
INSERT INTO hrstat_table(hrstat, txt, active_date, inactive_date) VALUES ('ADPT', 'Part-time Admin', null, null);
INSERT INTO hrstat_table(hrstat, txt, active_date, inactive_date) VALUES ('TLE', 'TLE', null, null);
INSERT INTO hrstat_table(hrstat, txt, active_date, inactive_date) VALUES ('EMER', 'Emeritus', null, null);
INSERT INTO hrstat_table(hrstat, txt, active_date, inactive_date) VALUES ('VEND', 'Vendor', null, null);
INSERT INTO hrstat_table(hrstat, txt, active_date, inactive_date) VALUES ('OTH', 'Other Employee', null, null);
INSERT INTO hrstat_table(hrstat, txt, active_date, inactive_date) VALUES ('PDG', 'Pending Employee', null, null);
INSERT INTO hrstat_table(hrstat, txt, active_date, inactive_date) VALUES ('STD', 'Student Worker', null, null);
INSERT INTO hrstat_table(hrstat, txt, active_date, inactive_date) VALUES ('CO', 'College Official', null, '2016-07-01');
INSERT INTO hrstat_table(hrstat, txt, active_date, inactive_date) VALUES ('SUM', 'Summer Worker', null, null);
INSERT INTO hrstat_table(hrstat, txt, active_date, inactive_date) VALUES ('PTGP', 'Part-time Fac GPS', null, null);
